-- Postgres schema, translated from the live SQLite database.
--
-- Two decisions here are load-bearing; getting either wrong loses data or
-- breaks writes, so both are spelled out rather than left to inference.
--
-- 1. BIGINT on the option-id columns.
--    Rayna option ids are not sequential — src/feed_cache.variant_synthetic_id()
--    derives them as SHA1(product:group:transfer)[:6] + 1e9, which currently
--    reaches 281,429,388,800,297. Postgres INTEGER stops at 2,147,483,647, so
--    these four columns must be BIGINT:
--        options.id
--        mappings.rayna_option_id
--        mappings.competitor_option_id
--        price_observations.option_id
--    Everything else measured under 512k and stays INTEGER.
--
-- 2. options.id keeps a sequence, and it is BY DEFAULT, not ALWAYS.
--    Rayna rows arrive with an explicit synthetic id. Competitor rows (the
--    URL-paste flow in backend.create_mapping_from_url) omit the id entirely
--    and rely on the database to assign one — under SQLite's AUTOINCREMENT
--    they land just above the synthetic range. So the column needs BOTH:
--    a sequence for the omitted case, and the freedom to accept an explicit
--    value for the synthetic case. GENERATED ALWAYS would reject the latter
--    and break every nightly sync.
--    003_reset_sequences.sql sets the sequence past the highest existing id.
--
-- Timestamps stay TEXT holding ISO-8601 strings, exactly as SQLite stored
-- them. Converting to TIMESTAMPTZ is a separate migration on purpose — the
-- app compares these as strings in places (the /mapped sort uses
-- localeCompare on created_at), so changing the type and the storage engine
-- in one step would mean debugging two migrations at once.

BEGIN;

-- ---------------------------------------------------------------- products
-- id comes from the Rayna feed, never generated here, so no sequence.
CREATE TABLE IF NOT EXISTS products (
    id           INTEGER PRIMARY KEY,
    name         TEXT NOT NULL,
    type         TEXT,
    city         TEXT,
    country      TEXT,
    market       TEXT NOT NULL,
    currency     TEXT NOT NULL,
    url          TEXT,
    raw_json     TEXT NOT NULL,
    ingested_at  TEXT NOT NULL
);

-- ------------------------------------------------------------- competitors
CREATE TABLE IF NOT EXISTS competitors (
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rayna_product_id      INTEGER NOT NULL REFERENCES products(id),
    market                TEXT NOT NULL,
    seller_domain         TEXT NOT NULL,
    seller_name           TEXT,
    seed_url              TEXT,
    snippet               TEXT,
    search_rank           INTEGER,
    search_query          TEXT,
    classified_as         TEXT,
    classifier_confidence DOUBLE PRECISION,
    classifier_reason     TEXT,
    sells_this_product    BOOLEAN,
    classified_at         TEXT,
    discovered_at         TEXT NOT NULL,
    UNIQUE (rayna_product_id, market, seller_domain)
);

-- ------------------------------------------------- competitor_listings
CREATE TABLE IF NOT EXISTS competitor_listings (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    competitor_id  INTEGER NOT NULL REFERENCES competitors(id),
    listing_url    TEXT NOT NULL,
    title          TEXT,
    raw_markdown   TEXT,
    raw_html       TEXT,
    scraped_at     TEXT NOT NULL,
    scrape_method  TEXT
);

-- ----------------------------------------------------------------- options
-- BIGINT + BY DEFAULT identity — see note 2 at the top of this file.
CREATE TABLE IF NOT EXISTS options (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source                 TEXT NOT NULL,
    rayna_product_id       INTEGER REFERENCES products(id),
    competitor_listing_id  INTEGER REFERENCES competitor_listings(id),
    name                   TEXT NOT NULL,
    pricing_basis          TEXT,
    price                  DOUBLE PRECISION,
    currency               TEXT,
    market                 TEXT NOT NULL,
    fingerprint_json       TEXT,
    raw_extracted_json     TEXT,
    extraction_model       TEXT,
    extracted_at           TEXT
);

-- ---------------------------------------------------------------- mappings
CREATE TABLE IF NOT EXISTS mappings (
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rayna_option_id       BIGINT NOT NULL REFERENCES options(id),
    competitor_option_id  BIGINT NOT NULL REFERENCES options(id),
    verdict               TEXT NOT NULL,
    confidence            DOUBLE PRECISION NOT NULL,
    diff_notes            TEXT,
    judge_model           TEXT,
    human_reviewed        BOOLEAN DEFAULT FALSE,
    human_verdict         TEXT,
    is_manual             BOOLEAN DEFAULT FALSE,
    created_at            TEXT NOT NULL,
    UNIQUE (rayna_option_id, competitor_option_id)
);

-- ------------------------------------------------------- price_observations
CREATE TABLE IF NOT EXISTS price_observations (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    option_id         BIGINT NOT NULL REFERENCES options(id),
    price             DOUBLE PRECISION NOT NULL,
    currency          TEXT NOT NULL,
    market            TEXT NOT NULL,
    target_date       TEXT,
    captured_at       TEXT NOT NULL,
    is_spike_flagged  BOOLEAN DEFAULT FALSE,
    capture_method    TEXT
);

-- ----------------------------------------------------------------- indexes
-- Carried over from SQLite.
CREATE INDEX IF NOT EXISTS idx_options_source              ON options (source);
CREATE INDEX IF NOT EXISTS idx_options_rayna_product       ON options (rayna_product_id);
CREATE INDEX IF NOT EXISTS idx_options_competitor_listing  ON options (competitor_listing_id);
CREATE INDEX IF NOT EXISTS idx_listings_competitor         ON competitor_listings (competitor_id);
CREATE INDEX IF NOT EXISTS idx_price_obs_option            ON price_observations (option_id);

-- New. SQLite never had these; the queries that need them were tolerable at
-- 44MB but each one is a sequential scan.
--   * /api/mapped joins mappings -> options -> products and filters is_manual
--   * _observations_for() looks up (option_id, target_date) for a whole page
--     of mappings at once
--   * the dashboard counts competitors per product
CREATE INDEX IF NOT EXISTS idx_mappings_rayna_option       ON mappings (rayna_option_id);
CREATE INDEX IF NOT EXISTS idx_mappings_competitor_option  ON mappings (competitor_option_id);
CREATE INDEX IF NOT EXISTS idx_mappings_is_manual          ON mappings (is_manual) WHERE is_manual;
CREATE INDEX IF NOT EXISTS idx_price_obs_option_date       ON price_observations (option_id, target_date);
CREATE INDEX IF NOT EXISTS idx_competitors_product         ON competitors (rayna_product_id);
CREATE INDEX IF NOT EXISTS idx_products_country_city       ON products (country, city);

COMMIT;
