-- RBAC: users, permissions, scopes, sessions, audit.
--
-- Model, as agreed:
--   * Two roles. 'admin' is unscoped and implicitly holds every permission.
--     'user' holds exactly what an admin grants.
--   * Permissions are per-action (11 of them), seeded below and referenced by
--     key so a typo fails loudly at insert time instead of silently granting
--     nothing.
--   * A user gets a role template, then per-user overrides on top. The
--     override row carries `granted`, so it can both add a permission the
--     template lacks and take away one the template includes.
--   * Data scope is country + city. Out of scope means hidden — reads filtered
--     and writes rejected — so the scope tables are consulted on every
--     product-touching query, not just at render time.
--
-- Enforcement lives in the API. These tables only record intent.

BEGIN;

-- ------------------------------------------------------------------- users
-- Email is stored lowercased; the application lowercases on the way in so the
-- plain UNIQUE below is a case-insensitive constraint in practice, without
-- needing the citext extension.
CREATE TABLE IF NOT EXISTS users (
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email                 TEXT NOT NULL UNIQUE,
    password_hash         TEXT NOT NULL,
    full_name             TEXT NOT NULL,
    role                  TEXT NOT NULL DEFAULT 'user',
    is_active             BOOLEAN NOT NULL DEFAULT TRUE,
    -- Admin sets a temporary password and hands it over; the user must
    -- replace it before the session can do anything else.
    must_change_password  BOOLEAN NOT NULL DEFAULT TRUE,
    -- The one account that cannot be demoted, deactivated or deleted, so the
    -- system can never be locked out of itself.
    is_owner              BOOLEAN NOT NULL DEFAULT FALSE,
    created_by            INTEGER REFERENCES users(id),
    created_at            TEXT NOT NULL,
    last_login_at         TEXT,
    CONSTRAINT users_role_valid CHECK (role IN ('admin', 'user'))
);

-- At most one owner, enforced by the database rather than by convention.
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_single_owner
    ON users ((TRUE)) WHERE is_owner;

CREATE INDEX IF NOT EXISTS idx_users_active ON users (is_active);

-- ------------------------------------------------------------- permissions
-- A fixed catalogue, not user-editable. Seeded at the bottom of this file.
CREATE TABLE IF NOT EXISTS permissions (
    key          TEXT PRIMARY KEY,
    label        TEXT NOT NULL,
    category     TEXT NOT NULL,
    description  TEXT NOT NULL,
    sort_order   INTEGER NOT NULL DEFAULT 0
);

-- --------------------------------------------------------- role templates
CREATE TABLE IF NOT EXISTS role_templates (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         TEXT NOT NULL UNIQUE,
    description  TEXT NOT NULL DEFAULT '',
    -- System templates ship with the app and cannot be deleted; admins may
    -- still create their own.
    is_system    BOOLEAN NOT NULL DEFAULT FALSE,
    created_by   INTEGER REFERENCES users(id),
    created_at   TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS role_template_permissions (
    template_id     INTEGER NOT NULL REFERENCES role_templates(id) ON DELETE CASCADE,
    permission_key  TEXT NOT NULL REFERENCES permissions(key),
    PRIMARY KEY (template_id, permission_key)
);

-- ------------------------------------------------------- user permissions
-- Applied on top of the user's template. `granted = FALSE` is a revoke, which
-- is why this is not just a membership table.
CREATE TABLE IF NOT EXISTS user_permissions (
    user_id         INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    permission_key  TEXT NOT NULL REFERENCES permissions(key),
    granted         BOOLEAN NOT NULL,
    PRIMARY KEY (user_id, permission_key)
);

-- Which template a user starts from. Nullable: a user can be built purely
-- from overrides.
ALTER TABLE users ADD COLUMN IF NOT EXISTS role_template_id
    INTEGER REFERENCES role_templates(id);

-- ------------------------------------------------------------- user scopes
-- One row per country, or per (country, city) pair. A row with city NULL
-- means every city in that country, including cities added later.
--
-- NULLS NOT DISTINCT matters here: by default Postgres treats two NULLs as
-- different values, so ('UAE', NULL) could be inserted twice. PG15+ lets the
-- constraint say otherwise.
CREATE TABLE IF NOT EXISTS user_scopes (
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id  INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    country  TEXT NOT NULL,
    city     TEXT,
    UNIQUE NULLS NOT DISTINCT (user_id, country, city)
);

CREATE INDEX IF NOT EXISTS idx_user_scopes_user ON user_scopes (user_id);

-- --------------------------------------------------------------- sessions
-- Server-side sessions. The cookie carries a random token; only its SHA-256
-- is stored, so a database leak does not hand over live sessions.
CREATE TABLE IF NOT EXISTS sessions (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash    TEXT NOT NULL UNIQUE,
    user_id       INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at    TEXT NOT NULL,
    last_seen_at  TEXT NOT NULL,
    -- Absolute expiry. Idle timeout is enforced against last_seen_at.
    expires_at    TEXT NOT NULL,
    ip            TEXT,
    user_agent    TEXT
);

CREATE INDEX IF NOT EXISTS idx_sessions_user    ON sessions (user_id);
CREATE INDEX IF NOT EXISTS idx_sessions_expires ON sessions (expires_at);

-- --------------------------------------------------------------- audit log
-- Every write, with enough context to answer "who did this and what changed"
-- long after the person has left. actor_email is denormalised on purpose:
-- the answer must survive the user row being edited or removed.
CREATE TABLE IF NOT EXISTS audit_log (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id INTEGER REFERENCES users(id),
    actor_email   TEXT NOT NULL,
    action        TEXT NOT NULL,
    entity_type   TEXT,
    entity_id     TEXT,
    before_json   JSONB,
    after_json    JSONB,
    ip            TEXT,
    created_at    TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_log (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_actor   ON audit_log (actor_user_id);
CREATE INDEX IF NOT EXISTS idx_audit_entity  ON audit_log (entity_type, entity_id);

-- ------------------------------------------------------------ attribution
-- Who created each piece of work. Nullable because everything that predates
-- RBAC has no author; 003 backfills those to the owner account.
ALTER TABLE mappings            ADD COLUMN IF NOT EXISTS created_by INTEGER REFERENCES users(id);
ALTER TABLE competitors         ADD COLUMN IF NOT EXISTS created_by INTEGER REFERENCES users(id);
ALTER TABLE competitor_listings ADD COLUMN IF NOT EXISTS created_by INTEGER REFERENCES users(id);

CREATE INDEX IF NOT EXISTS idx_mappings_created_by ON mappings (created_by);

-- ------------------------------------------------------ permission catalogue
INSERT INTO permissions (key, label, category, description, sort_order) VALUES
    ('mapped.view',              'View mapped pairs',      'view',
     'See /mapped — confirmed Rayna-competitor links and their price gaps.', 10),
    ('mapping.view',             'Open mapping workspace', 'view',
     'Browse products, options and competitors in the mapping workspace.', 20),
    ('comparison.view',          'View portfolio',         'view',
     'See the catalogue-wide comparison overview.', 30),

    ('mapping.create',           'Create mappings',        'work',
     'Link a Rayna option to a competitor option.', 40),
    ('mapping.delete',           'Unmap',                  'work',
     'Remove an existing mapping.', 50),
    ('competitor.add_url',       'Add competitor by URL',  'work',
     'Paste a seller URL to fetch and extract its options. Spends Claude credit.', 60),
    ('review.decide',            'Approve or reject',      'work',
     'Act on items in the review queue.', 70),

    ('competitor.delete_option', 'Delete an option',       'destructive',
     'Remove one extracted competitor option.', 80),
    ('competitor.delete_seller', 'Delete a seller',        'destructive',
     'Remove a competitor and every option beneath it.', 90),

    ('export.data',              'Export data',            'other',
     'Download mapped pairs and comparisons.', 100),
    ('admin.users',              'Manage users',           'other',
     'Create users, set permissions and scopes, manage templates.', 110)
ON CONFLICT (key) DO UPDATE SET
    label = EXCLUDED.label,
    category = EXCLUDED.category,
    description = EXCLUDED.description,
    sort_order = EXCLUDED.sort_order;

COMMIT;
